### PR TITLE
release CI

### PR DESCRIPTION
**Pull request by versecafe**
## Features
- Auto gens PR in sync with main to create change logs off changesets
- Creates github releases on PR merge
- Creates NPM releases on PR merge

## Prereq

- [x] NPM_TOKEN added to secrets
- [x] Allow GitHub Actions to create and approve pull requests set True

### CODE REVIEW

**Comment by benjreinhart** [comment]
How do we trigger a release, what is the process? Might be worth documenting this in the Contrib doc too?

**Comment by versecafe** [comment]
image

**Comment by benjreinhart** [comment]
When does the PR first open? What happens if something goes wrong in the process? Are there any docs I should at?

**Comment by versecafe** [comment]
The PR opens and updates on all commits to main, just keeps one synced PR, I think it also has a prerequisite that a version actually changed, it's built on top of changesets@v1 https://github.com/changesets/action

**Review by benjreinhart — APPROVED** [review]
I think a small addition to the contributing.md doc that explains the flow of create changeset -> release works would be helpful (and also what to do if something fails perhaps)

**Comment by versecafe** [comment]
> I think a small addition to the contributing.md doc that explains the flow of create changeset -> release works would be helpful (and also what to do if something fails perhaps)

Will add as long as everything goes smoothly with tomorrows test run of it

**Pull request merged**
