### PR TITLE
Homepage UI Rework!

### PR DESCRIPTION
**Pull request by versecafe**
New sections, new style, new feel, new app builder!

### CODE REVIEW

**Comment by versecafe** [comment]
## 831c537
image

**Comment by versecafe** [comment]
## [cf15665](https://github.com/srcbookdev/srcbook/pull/348/commits/cf15665f3ec893a9453c949934101e5c7156f623)
image

**Review by benjreinhart — COMMENTED** [review]
Is this still a draft? If not, code looks good to me and I can give a shipit.

**Comment by versecafe** [comment]
@benjreinhart draft part is over the styling of the Explore section and if I should make a modal menu like Create App has for JS/TS switch, once that's resolved I'd put it as ready to review

**Review by benjreinhart — APPROVED** [review]
re: copy, Srcbook was capitalized because it's a proper noun in the contexts it was used in. "notebook" is not in this context. So, rule of thumb would be that "apps" and "notebooks" would not be capitalized.

**Pull request merged**
